--- 
- hosts: azure_vm
  vars:
    local_repo: "./"
  tasks:

    - name: Create project directory in VM
      become: true
      ansible.builtin.file:
        path: /project
        state: directory
        mode: '0755'


    - name: Send the app to the VM 
      become: true
      copy:
        src: "{{ local_repo }}"
        dest: /project
        mode: 0644

     #Installer les dépendances sur le serveur
    - name: Install dependancies
      become: true
      ansible.builtin.apt: 
        pkg:
          - npm
          - nodejs
        state: latest
        update_cache: true

    - name: Npm Install
      command: npm install

    - name: Start the app 
      become: true
      command: npm start



    

