--- 
- hosts: azure_vm
  tasks:

    - name: Install dependancies
      become: true
      ansible.builtin.apt: 
        pkg:
          - npm
          - nodejs=18.0.0
        state: latest
        update_cache: true

    - name: Git Clone Repo 
      become: true
      ansible.builtin.git:
        repo: https://github.com/christmknd/CD-5IW.git
        dest: /home/azureuser/project
        clone: true
        update: true

    - name: Install Dependancies on project 

      become: true
      npm: 
        path: /home/azureuser/project

    - name: Build App
      become: true
      shell: npm run build 

    - name: Start App
      become: true
      shell: npm start /home/azureuser/project/main.ts



    

