--- 
- hosts: azure_vm

  tasks:
  

    - name: Delete folder if it exists 
      shell:  if [ -d "/home/azureuser/project" ]; then sudo rm -r /home/azureuser/project; fi

    - name: Git Clone Repo 
      become: true
      ansible.builtin.git:
        repo: https://github.com/christmknd/CD-5IW.git
        dest: /home/azureuser/project
        clone: true
        update: true

    - name: Install Dependancies on project 

      become: true
      npm: 
        path: /home/azureuser/project

    - name: Build App
      become: true
      shell: npm run build 

    - name: Start App
      become: true
      shell: npm start /home/azureuser/project/main.ts



    

