--- 
- hosts: azure_vm
  tasks:

    - name: Install dependancies
      become: true
      ansible.builtin.apt: 
        pkg:
          - npm
          - nodejs
        state: latest
        update_cache: true

    - name: Git Clone Repo 
      become: true
      ansible.builtin.git:
        repo: https://github.com/christmknd/CD-5IW.git
        dest: /home/azureuser/project
        clone: true
        update: true

    - name: Install
      become: true
      command: npm install 

    - name: Build
      command: npm run build 

    - name: Start the app 
      become: true
      command: npm start



    

