--- 
- hosts: azure_vm
  vars:
    NODEJS_VERSION: "8"
    ansible_distribution_release: "xenial" #trusty
  
  tasks:
    
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present

    - name: Install dependancies
      become: true
      ansible.builtin.apt: 
        name:
          - npm
        state: latest
        update_cache: true

    - name: Git Clone Repo 
      become: true
      ansible.builtin.git:
        repo: https://github.com/christmknd/CD-5IW.git
        dest: /home/azureuser/project
        clone: true
        update: true

    - name: Install Dependancies on project 

      become: true
      npm: 
        path: /home/azureuser/project

    - name: Build App
      become: true
      shell: npm run build 

    - name: Start App
      become: true
      shell: npm start /home/azureuser/project/main.ts



    

