--- 
- hosts: localhost
  tasks:

    - name: Create project directory in VM
      become: true
      ansible.builtin.file:
        path: /project
        state: directory
        mode: '0755'


    - name: Send the app to the VM 
      copy:
        src: /src
        dest: /project
        mode: 0644

     #Installer les dépendances sur le serveur
    - name: Install dependancies
      ansible.builtin.apt: 
        pkg:
          - node 
          - npm
          - pip3
        state: latest
        update_cache: true

    - name: Build and test the app 
      command : npm run build && npm run test

    - name: Start the app 
      command: npm start 


    

